# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
#before:
#  hooks:
#    # You may remove this if you don't use go modules.
#    - go mod download
#    # you may remove this if you don't need go generate
#    - go generate ./...

builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/golie/main.go
  binary: golie

  goos:
    - linux
    - windows
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64

archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  id: golie

  replacements:
    amd64: x86_64

  formats:
    - deb
    - rpm

  bindir: /usr/bin

  homepage: github.com/rolieup/golie
  license: CC0
  description: A client/server implementation of ROLIE written in GO
  release: 1
